name: github-pages-deploy
on:
  push:
    branches: [master]
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages
          folder: public
          ssh-key: ${{ secrets.DEPLOY_KEY }}
